version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - python --version
      - pip install --upgrade pip
      - pip install --upgrade aws-sam-cli
      - sam --version

  build:
    commands:
      - sam build --use-container
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset