version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - python --version
      - pip install --upgrade pip
      - pip install --upgrade aws-sam-cli
      - sam --version

  build:
    commands:
      - sam build --use-container
      
  post_build:
    commands:
      - sam deploy \
          --stack-name campo-vision \
          --s3-bucket ${ARTIFACT_BUCKET} \
          --s3-prefix ${ARTIFACT_FOLDER} \
          --capabilities CAPABILITY_IAM \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --region ${AWS_REGION}