AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Campo Vision - Telemetry System for Agricultural Equipment

Globals:
  Function:
    Timeout: 30
    Runtime: python3.12
    Architectures:
      - x86_64
    Environment:
      Variables:
        TELEMETRY_TABLE: !Ref TelemetryTable

Resources:
  # API Gateway
  TelemetryApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  # Lambda Functions
  IngestTelemetryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/ingest-telemetry/
      Handler: app.lambda_handler
      Environment:
        Variables:
          TELEMETRY_TABLE: !Ref TelemetryTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TelemetryTable
      Events:
        IngestAPI:
          Type: Api
          Properties:
            RestApiId: !Ref TelemetryApi
            Path: /telemetry
            Method: POST

  GetTelemetryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/get-telemetry/
      Handler: app.lambda_handler
      Environment:
        Variables:
          TELEMETRY_TABLE: !Ref TelemetryTable
      Events:
        GetAPI:
          Type: Api
          Properties:
            RestApiId: !Ref TelemetryApi
            Path: /telemetry
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TelemetryTable

  # DynamoDB Table
  TelemetryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: deviceId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: deviceId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: TimestampIndex
          KeySchema:
            - AttributeName: timestamp
              KeyType: HASH
          Projection:
            ProjectionType: ALL

Outputs:
  TelemetryApi:
    Description: "API Gateway endpoint URL for Prod stage for Telemetry functions"
    Value: !Sub "https://${TelemetryApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  IngestTelemetryFunction:
    Description: "Ingest Telemetry Lambda Function ARN"
    Value: !GetAtt IngestTelemetryFunction.Arn
  GetTelemetryFunction:
    Description: "Get Telemetry Lambda Function ARN"
    Value: !GetAtt GetTelemetryFunction.Arn
  TelemetryTable:
    Description: "DynamoDB Table for Telemetry Data"
    Value: !Ref TelemetryTable
