AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Campo Vision - Telemetry System for Agricultural Equipment

Globals:
  Function:
    Timeout: 30
    Runtime: python3.12
    Architectures:
      - x86_64
    Environment:
      Variables:
        TELEMETRY_TABLE: !Ref TelemetryTable
        USER_POOL_ID: !Ref CampoVisionUserPool
        USER_POOL_CLIENT_ID: !Ref CampoVisionUserPoolClient

Resources:
  # Cognito User Pool
  CampoVisionUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: CampoVisionUserPool
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true

  # Cognito User Pool Client
  CampoVisionUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: CampoVisionClient
      UserPoolId: !Ref CampoVisionUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      PreventUserExistenceErrors: ENABLED

  # Lambda Layer for common code
  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: campo-vision-common-layer
      Description: Common code for Campo Vision Lambda functions
      ContentUri: ./layers
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Retain

  # API Gateway
  TelemetryApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt CampoVisionUserPool.Arn
        AddDefaultAuthorizerToCorsPreflight: false

  # Lambda Functions
  IngestTelemetryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/ingest-telemetry/
      Handler: app.lambda_handler
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          TELEMETRY_TABLE: !Ref TelemetryTable
          USER_POOL_ID: !Ref CampoVisionUserPool
          USER_POOL_CLIENT_ID: !Ref CampoVisionUserPoolClient
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TelemetryTable
      Events:
        IngestAPI:
          Type: Api
          Properties:
            RestApiId: !Ref TelemetryApi
            Path: /telemetry
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer

  GetTelemetryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/get-telemetry/
      Handler: app.lambda_handler
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          TELEMETRY_TABLE: !Ref TelemetryTable
          USER_POOL_ID: !Ref CampoVisionUserPool
          USER_POOL_CLIENT_ID: !Ref CampoVisionUserPoolClient
      Events:
        GetAPI:
          Type: Api
          Properties:
            RestApiId: !Ref TelemetryApi
            Path: /telemetry
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TelemetryTable

  # DynamoDB Table
  TelemetryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: deviceId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: deviceId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: TimestampIndex
          KeySchema:
            - AttributeName: timestamp
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  # Company Table
  CompanyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: companyId
          AttributeType: S
      KeySchema:
        - AttributeName: companyId
          KeyType: HASH

  # Device Table
  DeviceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: deviceId
          AttributeType: S
        - AttributeName: companyId
          AttributeType: S
      KeySchema:
        - AttributeName: deviceId
          KeyType: HASH
        - AttributeName: companyId
          KeyType: RANGE

Outputs:
  TelemetryApi:
    Description: "API Gateway endpoint URL for Prod stage for Telemetry functions"
    Value: !Sub "https://${TelemetryApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  IngestTelemetryFunction:
    Description: "Ingest Telemetry Lambda Function ARN"
    Value: !GetAtt IngestTelemetryFunction.Arn
  GetTelemetryFunction:
    Description: "Get Telemetry Lambda Function ARN"
    Value: !GetAtt GetTelemetryFunction.Arn
  TelemetryTable:
    Description: "DynamoDB Table for Telemetry Data"
    Value: !Ref TelemetryTable
  CompanyTable:
    Description: "DynamoDB Table for Company Data"
    Value: !Ref CompanyTable
  DeviceTable:
    Description: "DynamoDB Table for Device Data"
    Value: !Ref DeviceTable
  CampoVisionUserPoolId:
    Description: "Cognito User Pool ID"
    Value: !Ref CampoVisionUserPool
  CampoVisionUserPoolClientId:
    Description: "Cognito User Pool Client ID"
    Value: !Ref CampoVisionUserPoolClient
